### ISSUE TITLE
 \item Method3 uses  $F=0.5$ to find its deltas;

### ISSUE THREAD

**Issue by timm** [ai-se/crossTrees#10]
where"? i dont see F

and our convention is greek characters for magic params. 

better not rename F delta or episilon

use omega

t

**Comment by rahlk** [comment]
Sure..

**Comment by rahlk** [comment]
Remeber the mutation extent? That's F (now omega)

**Comment by timm** [comment]
cant find F or omega in 4.1.3

**Comment by rahlk** [comment]
Adding now, on proof reads I jotted down some minor edits to 4.1.3 (this includes omega)

**Comment by rahlk** [comment]
Done: Comments?

Method3 generates clusters from the training data just like Method1. Following this, it summarizes the clusters $C_X$ using ``Best-In-Cluster'' $B_X$, which is (1) the centroid of the cluster for the Jureczko data; (2) the cluster's member with the fastest runtime for the Seigmund data. Following this, Method3 connects  each cluster $C_i$ to a nearest neighbor $C_j$ by a {\em gradient}. Each gradient has a (bottom,top) end labelled  ($C_i,C_j$) containing the (worst,best) performance scores, respectively. 

For each test instance, Method3 finds the nearest gradient, the runs up to the top (best) end $C_j$, then extracts $B_j$ (which is the best-in-cluster associated with  $C_j$). The returned plan is then computed as a fraction ($\omega=0.5$) of the delta between the test case and it's corresponding $B_j$.

**Comment by timm** [comment]
> The returned plan is then computed as a fraction ($\omega=0.5$) of the delta between the test case and it's corresponding $B_j$.

unclear. \omega of the distance or \omeaga on number of features?

**Comment by rahlk** [comment]
I'll rephrase. 
I mutate all features half way between test case and B_j

**Comment by rahlk** [comment]
So technically distance.
