### ISSUE TITLE
fig14 odd

### ISSUE THREAD

**Issue by timm** [ai-se/crossTrees#11]
not seeing a 51.5 on xtree

also, please round 5.15, 2.75. 2.2 2.9 to 52,3,3,3
![image](https://cloud.githubusercontent.com/assets/29195/9553868/e92a2f6c-4d8f-11e5-847d-0ed03111c4b9.png)

**Comment by timm** [comment]
these comments on "R" are no longer correct. and that is a detail that could hang us with reviewers

![image](https://cloud.githubusercontent.com/assets/29195/9554818/bd7d88da-4d96-11e5-8cd5-88930cfb9729.png)

**Comment by rahlk** [comment]
They still hold don't they? Wait 
![image](https://cloud.githubusercontent.com/assets/1433964/9554895/4fe7c1d6-4d97-11e5-87c0-376fe7b80920.png)
Now?

**Comment by rahlk** [comment]
For instance, in fig 14 R<0: CD, CD+FS makes this worse.

**Comment by timm** [comment]
hangon... 

u r right. my bad
